In [609]:
import numpy as np
import pandas as pd

hydration_after_p = 0.8
hydration_before_p = 0.045
#Wet Weight(g) after pretreatment
#2% 1h, 12% 1h, 2% 3h 12% 3h
w_60c= np.array([7.8302,4.0316,5.45,4.48]) 
w_80c= np.array([6.4508, 5.181, 5.929, 3.9756]) 
w_100c = np.array([5.6054, 4.1634, 5.9361, 3.9318]) 
w_120c = np.array([4.8918, 3.3319, 5.1648, 2.9348]) 

#Dry Weight(g) after pretreatment
dry_w_60c = w_60c * (1-hydration_after_p)
dry_w_80c = w_80c * (1-hydration_after_p)
dry_w_100c = w_100c * (1-hydration_after_p)
dry_w_120c = w_120c * (1-hydration_after_p)

avg_lost_w_60c = dry_w_60c/2
avg_lost_w_80c = dry_w_80c/2
avg_lost_w_100c = dry_w_100c/2
avg_lost_w_120c = dry_w_120c/2

avg_lost_w_60c, avg_lost_w_80c, avg_lost_w_100c, avg_lost_w_120c

In [610]:
def calculate_dry_weight(w, hydration_after_p):
    return w * (1 - hydration_after_p)

def calculate_hplc(hplc, k, m, dilution_factor=5):
    return np.array([dilution_factor*(value-m)/k for value in hplc])

def calculate_mass(c, volume_H):
    return c * volume_H

def calculate_max(values, dry_masses):
    return [values[i]*value for i, value in enumerate(dry_masses)]

def calculate_yield(m, max_m):
    return np.divide(m, max_m)

def calculate_average(pairs):
    return np.mean(pairs, axis=1)

def reshape_into_pairs(array):
    return array.reshape(-1, 2)

def format(input_array):
    multiplied_array = input_array * 100
    str_array = np.array(multiplied_array, dtype=str)
    extracted_array = np.array([x[:4] for x in str_array])
    return extracted_array

def format2(input_array):
    str_array = np.array(input_array, dtype=str)
    extracted_array = np.array([x[:4] for x in str_array])
    return extracted_array


In [611]:
def preprocess_data(G_samples_hplc, XMG_samples_hplc, glucose_yields, xylmangal_values, volume, dry_masses_after_p, dry_masses_before_pretreatment):



    pairs_G_C = reshape_into_pairs(G_samples_hplc)
    pairs_XMG_C = reshape_into_pairs(XMG_samples_hplc)

    avgs_G_C = calculate_average(pairs_G_C)
    avgs_XMG_C = calculate_average(pairs_XMG_C)
  
    c_G = calculate_hplc(avgs_G_C, k=315718, m=4623)
    c_XMG = calculate_hplc(avgs_XMG_C, k=317400, m=10216)
    
    m_G_before = calculate_mass(c_G, volume)
    m_XMG_before = calculate_mass(c_XMG, volume)

    #Kompensera för att vi inte tog allt när vi gjorde hplc
    wet_mass_into_hplc = 2 #g
    moisture = 0.8
    dried_sample = wet_mass_into_hplc * (1-moisture)
    multiply_factor_over_pretreatment = dry_masses_after_p/dried_sample

    m_G = m_G_before * multiply_factor_over_pretreatment
    m_XMG = m_XMG_before * multiply_factor_over_pretreatment

    #Yield
    yield_glucose_procent_process = calculate_yield(m_G, dry_masses_before_pretreatment)
    yield_XMG_procent_process = calculate_yield(m_XMG, dry_masses_before_pretreatment)
    yield_monosacharides_procent_process = np.add(yield_glucose_procent_process, yield_XMG_procent_process)

    #Selectivity
    selectivity_glucose_procent_process = np.divide(m_G, dry_masses_after_p)
    selectivity_XMG_procent_process = np.divide(m_XMG, dry_masses_after_p)
    selectivity_monosacharices_procent_process = np.divide(m_G+m_XMG, dry_masses_after_p)
    

    results = {
        "Dry W Milled(g)": format2(dry_masses_before_pretreatment),
        "Dry W after Pretreatment(g)": format2(dry_masses_after_p),

        "Glucose(g) ": format2(m_G),
        "XMG(g)": format2(m_XMG),
        "Monosacharides(g)": format2(np.add(m_G, m_XMG)),

        "Selctivity Glucose (%)": format(selectivity_glucose_procent_process),
        "Selctivity XMG (%)": format(selectivity_XMG_procent_process),
        "Selctivity Monosacharides (%)": format(selectivity_monosacharices_procent_process),

        "Yield Glucose (%)": format(yield_glucose_procent_process),
        "Yield XMG (%)": format(yield_XMG_procent_process),
        "Yield Monosacharides (%)": format(yield_monosacharides_procent_process),
    }

    return results

In [612]:
#Varmast 1h, varmast 3h, kallast 1h, kallast 3h
#Ex 120C 1h, 120C 3h, 60C 1h, 60C 3h

#CHANGE THESE
milled_masses = np.array([2.0924,2.0960,2.0954,2.0985,2.0923,2.0979,2.0962,2.0943])
Glucose_samples_hplc = np.array([590520.1774,  626867.5736, 693851.4441, 661331.5045, 578989.8003, 675418.0375, 571507.7927, 596580.4333])
XMG_samples_hplc = np.array([149706.8617, 159126.8929,  176542.8571,  168805.7143,  147914.2857,  172857.1429,  146857.1429,  153200.0000])

#Constants
glucose_yields = np.array([39.54, 88.30, 68.42, 65.11, 56.28])/100
xylmangal_values = np.array([25.24, 2.64, 1.97, 9.96, 7.4])/100
volume = 0.02485
hydration_after_p = 0.8

dry_masses_before_p = milled_masses*0.955
average_dry_masses_before_pretreatment = calculate_average(reshape_into_pairs(dry_masses_before_p))
a = average_dry_masses_before_pretreatment

#CHANGE THIS 
dry_masses_after_p = np.array([a[0]*avg_lost_w_120c[0], a[1]*avg_lost_w_120c[2], a[2]*avg_lost_w_60c[0], a[3]*avg_lost_w_60c[2]])


In [613]:
data = preprocess_data(Glucose_samples_hplc, XMG_samples_hplc, glucose_yields, xylmangal_values, volume, dry_masses_after_p, average_dry_masses_before_pretreatment)


index = ['120C 1h', '120C 3h', '60C 1h', '60C 3h']
process_data_keys = [
    "Dry W Milled(g)",
    "Dry W after Pretreatment(g)",
    "Glucose(g) ",
    "XMG(g)",
    "Monosacharides(g)",
    "Yield Glucose (%)",
    "Yield XMG (%)",
    "Yield Monosacharides (%)",
    "Selctivity Glucose (%)",
    "Selctivity XMG (%)",
    "Selctivity Monosacharides (%)"
]

# Create dataframes
process_data = {key: data[key] for key in process_data_keys}
process_df = pd.DataFrame(process_data)
process_df.index = index

print('2% NaOH batch - Process Data')
print(f"NREL Yield Glucose: {39.54}")
print(f"NREL Yield XMG: {25.24}")
print(f"NREL Yield Monosacharides: {39.54+25.24}")
print()
process_df



2% NaOH batch - Process Data
NREL Yield Glucose: 39.54
NREL Yield XMG: 25.24
NREL Yield Monosacharides: 64.78



Dry W Milled(g) Dry W after Pretreatment(g) Glucose(g)  XMG(g)  \
120C 1h            1.99                        0.97        0.58   0.13   
120C 3h            2.00                        1.03        0.68   0.16   
60C 1h             2.00                        1.56        0.95   0.23   
60C 3h             2.00                        1.09        0.62   0.14   

        Monosacharides(g) Yield Glucose (%) Yield XMG (%)  \
120C 1h              0.71              29.0          6.90   
120C 3h              0.84              34.1          8.21   
60C 1h               1.18              47.9          11.5   
60C 3h               0.77              31.0          7.45   

        Yield Monosacharides (%) Selctivity Glucose (%) Selctivity XMG (%)  \
120C 1h                     35.9                   59.4               14.1   
120C 3h                     42.4                   66.2               15.8   
60C 1h                      59.4                   61.2               14.6   
60C 3h                      38.5                   57.0               13.6   

        Selctivity Monosacharides (%)  
120C 1h                          73.5  
120C 3h                          82.1  
60C 1h                           75.9  
60C 3h                           70.6

In [614]:
#Values

#Varmast 1h, varmast 3h, kallast 1h, kallast 3h
#Ex 120C 1h, 120C 3h, 60C 1h, 60C 3h

#2% NaOH 60-120%
milled_masses = np.array([2.0924,2.0960,2.0954,2.0985,2.0923,2.0979,2.0962,2.0943])
Glucose_samples_hplc = np.array([590520.1774,  626867.5736, 693851.4441, 661331.5045, 578989.8003, 675418.0375, 571507.7927, 596580.4333])
XMG_samples_hplc = np.array([149706.8617, 159126.8929,  176542.8571,  168805.7143,  147914.2857,  172857.1429,  146857.1429,  153200.0000])


dry_masses_after_p = np.array([a[0]*avg_lost_w_120c[0], a[1]*avg_lost_w_120c[2], a[2]*avg_lost_w_60c[0], a[3]*avg_lost_w_60c[2]])

#12% NaOH 60-120% 

#12% NaOH 80-100%

#2% NaOH 80-100%


In [615]:
def create_dataframe(Glucose_samples_hplc, XMG_samples_hplc, indices, dry_masses_before_p,dry_masses_after_p):
    #Constants
    volume = 0.02485
    glucose_yields = np.array([39.54, 88.30, 68.42, 65.11, 56.28])/100,
    xylmangal_values = np.array([25.24, 2.64, 1.97, 9.96, 7.4])/100
    

    data = preprocess_data(Glucose_samples_hplc, XMG_samples_hplc, glucose_yields, xylmangal_values, volume, dry_masses_after_p, dry_masses_before_p)

    process_data_keys = [
        "Dry W Milled(g)",
        "Dry W after Pretreatment(g)",
        "Glucose(g) ",
        "XMG(g)",
        "Monosacharides(g)",
        "Yield Glucose (%)",
        "Yield XMG (%)",
        "Yield Monosacharides (%)",
        "Selctivity Glucose (%)",
        "Selctivity XMG (%)",
        "Selctivity Monosacharides (%)"
    ]

    # Create dataframes
    process_data = {key: data[key] for key in process_data_keys}
    process_df = pd.DataFrame(process_data)
    process_df.index = indices

   

    return process_df


In [618]:
#2% NaOH 60-120%
milled_masses_1 = np.array([2.0924, 2.0960, 2.0954, 2.0985, 2.0923, 2.0979, 2.0962, 2.0943])
dry_masses_before_p_1 = milled_masses_1*0.955
avg_before_p_1 = calculate_average(reshape_into_pairs(dry_masses_before_p_1))
a_1 = avg_before_p_1
dry_masses_after_p_1 = np.array([a_1[0]*avg_lost_w_120c[0], a_1[1]*avg_lost_w_120c[2], a_1[2]*avg_lost_w_60c[0], a_1[3]*avg_lost_w_60c[2]])


#12% NaOH 60-120% 
milled_masses_2 = np.array([2.0924, 2.0960, 2.0954, 2.0985, 2.0923, 2.0979, 2.0962, 2.0943])
dry_masses_before_p_2 = milled_masses_2*0.955
avg_before_p_2 = calculate_average(reshape_into_pairs(dry_masses_before_p_2))
a_2 = avg_before_p_2
dry_masses_after_p_2 = np.array([a_2[0]*avg_lost_w_120c[1], a_2[1]*avg_lost_w_120c[3], a_2[2]*avg_lost_w_60c[1], a_2[3]*avg_lost_w_60c[3]])


#12% NaOH 80-100%
milled_masses_3 = np.array([2.0003, 2.0024, 1.9970, 2.0050, 2.0008, 1.9008, 1.9980, 2.002])
dry_masses_before_p_3 = milled_masses_3*0.955

avg_before_p_3 = calculate_average(reshape_into_pairs(dry_masses_before_p_3))
a_3 = avg_before_p_3
dry_masses_after_p_3 = np.array([a_3[0]*avg_lost_w_100c[1], a_3[1]*avg_lost_w_100c[3], a_3[2]*avg_lost_w_80c[1], a_3[3]*avg_lost_w_80c[3]])


#2% NaOH 80-100%
milled_masses_4 = np.array([2.0040, 1.9977, 1.9997, 2.0030, 2.0003, 1.9984, 2.0020, 1.9966])
dry_masses_before_p_4 = milled_masses_4*0.955
avg_before_p_4 = calculate_average(reshape_into_pairs(dry_masses_before_p_4))
a_4 = avg_before_p_4
dry_masses_after_p_4 = np.array([a_4[0]*avg_lost_w_100c[0], a_4[1]*avg_lost_w_100c[2], a_4[2]*avg_lost_w_80c[0], a_4[3]*avg_lost_w_80c[2]])

#avg_before_p_1, avg_before_p_2, avg_before_p_3, avg_before_p_4
dry_masses_after_p_1, dry_masses_after_p_2, dry_masses_after_p_3, dry_masses_after_p_4

(array([0.97834092, 1.03429626, 1.56668247, 1.09052524]),
 array([0.66636701, 0.58771931, 0.80665079, 0.89643176]),
 array([0.79574617, 0.75134929, 0.96522755, 0.7593396 ]),
 array([1.07108642, 1.13456041, 1.23170237, 1.13204265]))

In [617]:
studies = [
    {
        "Glucose_samples_hplc": np.array([590520.1774, 626867.5736, 693851.4441, 661331.5045, 578989.8003, 675418.0375, 571507.7927, 596580.4333]),
        "XMG_samples_hplc": np.array([149706.8617, 159126.8929, 176542.8571, 168805.7143, 147914.2857, 172857.1429, 146857.1429, 153200.0000]),
        "dry_masses_after_p": dry_masses_after_p_1,
        "dry_masses_before_p": avg_before_p_1,
        "indices": ['120C 1h', '120C 3h', '60C 1h', '60C 3h']
     },
    {
        "Glucose_samples_hplc": np.array([1164687.9925, 1239731.5045, 1379701.5045, 1312666.1654, 1157971.6083, 1351166.1654, 1141166.1654, 1197971.6083]),
        "XMG_samples_hplc": np.array([0, 0, 0, 0, 103180.0916, 106556.1953, 79071.6490, 74139.5075]),
        "dry_masses_after_p": dry_masses_after_p_2,
        "dry_masses_before_p": avg_before_p_2,
        "indices": ['120C 1h', '120C 3h', '60C 1h', '60C 3h']
    },
    {
        "Glucose_samples_hplc": np.array([1084281.8242, 1437375.2409, 1095570.4941, 1269949.5440, 0,0, 1125741.7195, 1193543.1789]),
        "XMG_samples_hplc": np.array([0, 97365.4265, 0, 0, 0, 0, 0, 0]),
        "dry_masses_after_p": dry_masses_after_p_3,
        "dry_masses_before_p": avg_before_p_3,
        "indices": ['100C 1h', '100C 3h', '80C 1h', '80C 3h']

    },
    {
        "Glucose_samples_hplc": np.array([804353.4156, 739282.6040, 745575.4034, 745801.7998, 727440.5672, 924715.2307, 880340.6993, 899655.9408]),
        "XMG_samples_hplc": np.array([0, 154173.2942, 195054.4891, 202082.0536, 159049.2005, 205812.6120, 189111.6415, 190132.9875]),
        "dry_masses_after_p": dry_masses_after_p_4,
        "dry_masses_before_p": avg_before_p_4,
        "indices": ['100C 1h', '100C 3h', '80C 1h', '80C 3h']
    }
]

# For each study, create a dataframe and store it in a list
dataframes = []
print(f"NREL Yield Glucose: {39.54}")
print(f"NREL Yield XMG: {25.24}")
print(f"NREL Yield Monosacharides: {39.54+25.24}")
print()
labels = [['2% 60-120'], ['12% 60-120'], ['12% 80-100'], ['2% 80-100']]
for i, study in enumerate(studies):
    df = create_dataframe(**study)
    styled_df = df.style.background_gradient(cmap='viridis')
    dataframes.append(styled_df)
    print(f'Data for study: {labels[i][0]}:')
    display(styled_df)



NREL Yield Glucose: 39.54
NREL Yield XMG: 25.24
NREL Yield Monosacharides: 64.78

Data for study: 2% 60-120:


Data for study: 12% 60-120:


Data for study: 12% 80-100:


Data for study: 2% 80-100:
