In [113]:
import matplotlib.pyplot as plt
import numpy as np

In [114]:
def linreg_glucose(hplc: list):
    k = 315718
    m = 4623
    dilution_factor = 5
    y_values = np.array([dilution_factor*(value-m)/k for value in hplc])
    return y_values

def linreg_XMG(hplc: list):
    k = 317400
    m = 10216
    dilution_factor = 5
    y_values = np.array([dilution_factor*(value-m)/k for value in hplc])
    return y_values


#Constants
volume = 0.02485 #L
hydration_after_p = 0.8
hydration_before_p = 0.045
weight_before = 2.09
dry_weight_before = weight_before * (1-hydration_before_p)

#Wet Weight(g) after pretreatment
#2% 1h, 12% 1h, 2% 3h 12% 3h
w_60c= np.array([7.8302,4.0316,5.45,4.48]) 
w_80c= np.array([6.4508, 5.181, 5.929, 3.9756]) 
w_100c = np.array([5.6054, 4.1634, 5.9361, 3.9318]) 
w_120c = np.array([4.8918, 3.3319, 5.1648, 2.9348]) 

#Dry Weight(g) after pretreatment
dry_w_60c = w_60c * (1-hydration_after_p)
dry_w_80c = w_80c * (1-hydration_after_p)
dry_w_100c = w_100c * (1-hydration_after_p)
dry_w_120c = w_120c * (1-hydration_after_p)

dry_w_60c, dry_w_80c, dry_w_100c, dry_w_120c


(array([1.56604, 0.80632, 1.09   , 0.896  ]),
 array([1.29016, 1.0362 , 1.1858 , 0.79512]),
 array([1.12108, 0.83268, 1.18722, 0.78636]),
 array([0.97836, 0.66638, 1.03296, 0.58696]))

In [115]:
#NREL pretreatment data Glucose, XylManGal, Lignin, Ash, Other in %
 
macro_labels = np.array(['Glucose', 'XylManGal', 'Lignin', 'Ash', 'Other'])
nrel_milled = np.array([39.54,25.24,30.9,13.02,1.3])
nrel_120_1h = np.array([88.30,2.64,7.89,3.73,-2.56])
nrel_120_3h = np.array([68.42,1.97,8.12,3.08,18.41])  
nrel_60_1h = np.array([65.11,9.96,16.75,5.96,2.23])
nrel_60_3h = np.array([56.28,7.4,15.68,7.38,13.26])

p_labels = np.array(['nrel_milled', 'nrel_120_1h', 'nrel_120_3h', 'nrel_60_1h', 'nrel_60_3h'])
glucose_values = np.array([39.54, 88.30, 68.42, 65.11, 56.28])/100
xylmangal_values = np.array([25.24, 2.64, 1.97, 9.96, 7.4])/100
lignin_values = np.array([30.9, 7.89, 8.12, 16.75, 15.68])/100
lsh_values = np.array([13.02, 3.73, 3.08, 5.96, 7.38])/100
other_values = np.array([1.3, -2.56, 18.41, 2.23, 13.26])/100

monosacharides = np.add(glucose_values, xylmangal_values)

nrel_data = {
    "nrel_milled": {
        'Glucose': 0.3954,
        'XylManGal': 0.2524,
        'Lignin': 0.309,
        'Ash': 0.1302,
        'Other': 0.013
    },
    "nrel_120_1h": {
        'Glucose': 0.883,
        'XylManGal': 0.0264,
        'Lignin': 0.0789,
        'Ash': 0.0373,
        'Other': -0.0256
    },
    "nrel_120_3h": {
        'Glucose': 0.6842,
        'XylManGal': 0.0197,
        'Lignin': 0.0812,
        'Ash': 0.0308,
        'Other': 0.1841
    },
    "nrel_60_1h": {
        'Glucose': 0.6511,
        'XylManGal': 0.0996,
        'Lignin': 0.1675,
        'Ash': 0.0596,
        'Other': 0.0223
    },
    "nrel_60_3h": {
        'Glucose': 0.5628,
        'XylManGal': 0.074,
        'Lignin': 0.1568,
        'Ash': 0.0738,
        'Other': 0.1326
    }
}



In [117]:
#2% 60-120C 
#120C 1h, 120C 3h, 60C 1h, 60C 3h
labels_2_60_120 = []
masses_before_p = np.array([2.0924,2.0960,2.0954,2.0985,2.0923,2.0979,2.0962,2.0943])
G_samples_hplc = np.array([590520.1774,  626867.5736, 693851.4441, 661331.5045, 578989.8003, 675418.0375, 571507.7927, 596580.4333])
XMG_samples_hplc = np.array([149706.8617, 159126.8929,  176542.8571,  168805.7143,  147914.2857,  172857.1429,  146857.1429,  153200.0000])

# Reshape the array into pairs of samples
pairs_masses = masses_before_p.reshape(-1, 2)
pairs_G_C = G_samples_hplc.reshape(-1, 2)
pairs_XMG_C = XMG_samples_hplc.reshape(-1, 2)

# Calculate the avg of each pair
avgs_masses = np.mean(pairs_masses, axis=1)
avgs_G_C = np.mean(pairs_G_C, axis=1)
avgs_XMG_C = np.mean(pairs_XMG_C, axis=1)
dry_masses = avgs_masses*(1-hydration_after_p)

c_G = linreg_glucose(avgs_G_C)
c_XMG = linreg_XMG(avgs_XMG_C)
print(f"c_XMG: {c_XMG}, c_G: {c_G}")
m_G = c_G * volume_H
m_XMG = c_XMG * volume_H

#Over pretreatment
max_glucose_p = np.array([glucose_values[i+1]*value for i, value in enumerate(dry_masses)])
max_XMG_p = np.array([xylmangal_values[i+1]*value for i, value in enumerate(dry_masses)])

yield_glucose_p = np.divide(m_G,max_glucose_p)
yield_XMG_p = np.divide(m_XMG,max_XMG_p)

#Over raw
max_glucose_r = glucose_values[0]
max_XMG_r = xylmangal_values[0]

yield_glucose_r = np.divide(m_G,max_glucose_r)
yield_XMG_r = np.divide(m_XMG,max_XMG_r)

#Total over pretreatment
max_monosacharides = np.array([monosacharides[i+1]*value for i, value in enumerate(dry_masses)])
yield_monosacharides_p = np.divide(m_G+m_XMG,max_monosacharides)

#Total over raw
max_monosacharides = np.array([monosacharides[0]])
yield_monosacharides_r = np.divide(m_G+m_XMG,max_monosacharides)

print(f"dry total mass in samples {dry_masses}")
print(f"mass XMG in samples: {m_XMG}")
print(f"mass Glucose in samples: {m_G}")
print(f"max glucose %: {max_glucose_r}")
print(f"max XMG %: {max_XMG_r}")
print(f"yield glucose over pretreatment: {yield_glucose_p}")
print(f"yield XMG over pretreatment: {yield_XMG_p}")
print(f"yield glucose over raw: {yield_glucose_r}")
print(f"yield XMG over raw: {yield_XMG_r}")
print(f"yield monosacharides over pretreatment: {yield_monosacharides_p}")
print(f"yield monosacharides over raw: {yield_monosacharides_r}")






c_XMG: [2.27159542 2.55920425 2.36562247 2.20246647], c_G: [ 9.56662077 10.65774638  9.85976281  9.17624451]
dry total mass in samples [0.41884 0.41939 0.41902 0.41905]
mass XMG in samples: [0.05644915 0.06359623 0.05878572 0.05473129]
mass Glucose in samples: [0.23773053 0.264845   0.24501511 0.22802968]
max glucose %: 0.3954
max XMG %: 0.25239999999999996
yield glucose over pretreatment: [0.64280034 0.92297648 0.89807046 0.96687746]
yield XMG over pretreatment: [5.1051123  7.69745297 1.40856774 1.76497327]
yield glucose over raw: [0.60124058 0.66981537 0.6196639  0.57670631]
yield XMG over raw: [0.22364955 0.25196603 0.23290697 0.21684347]
yield monosacharides over pretreatment: [0.77234183 1.11257328 0.96580129 1.05962101]
yield monosacharides over raw: [0.45412114 0.50701022 0.46897318 0.43649424]
